//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbImage
    {
        public tbImage()
        {
            this.tbImageComments = new HashSet<tbImageComment>();
            this.tbImageMetas = new HashSet<tbImageMeta>();
            this.tbUserImages = new HashSet<tbUserImage>();
        }
    
        public System.Guid Id { get; set; }
        public long UploaderUserId { get; set; }
        public bool IsLocked { get; set; }
        public decimal Price { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsSold { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public bool IsPublic { get; set; }
    
        public virtual tbProfile tbProfile { get; set; }
        public virtual ICollection<tbImageComment> tbImageComments { get; set; }
        public virtual ICollection<tbImageMeta> tbImageMetas { get; set; }
        public virtual ICollection<tbUserImage> tbUserImages { get; set; }
    }
}
