//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbImageMeta
    {
        public tbImageMeta()
        {
            this.tbImageMeta1 = new HashSet<tbImageMeta>();
        }
    
        public long Id { get; set; }
        public System.Guid ImageId { get; set; }
        public Nullable<long> ParentMetaId { get; set; }
        public int MetaTypeId { get; set; }
        public string MetaValue { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual tbImage tbImage { get; set; }
        public virtual ICollection<tbImageMeta> tbImageMeta1 { get; set; }
        public virtual tbImageMeta tbImageMeta2 { get; set; }
        public virtual tbMetaType tbMetaType { get; set; }
    }
}
