//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProfile
    {
        public tbProfile()
        {
            this.tbImages = new HashSet<tbImage>();
            this.tbImageComments = new HashSet<tbImageComment>();
            this.tbUserImages = new HashSet<tbUserImage>();
        }
    
        public long Id { get; set; }
        public string UserId { get; set; }
    
        public virtual ICollection<tbImage> tbImages { get; set; }
        public virtual ICollection<tbImageComment> tbImageComments { get; set; }
        public virtual ICollection<tbUserImage> tbUserImages { get; set; }
    }
}
