//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUserImage
    {
        public long Id { get; set; }
        public long ProfileId { get; set; }
        public System.Guid ImageId { get; set; }
        public bool IsOwner { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime PurchaseDateTime { get; set; }
        public decimal PurchasePrice { get; set; }
    
        public virtual tbImage tbImage { get; set; }
        public virtual tbProfile tbProfile { get; set; }
    }
}
