//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuth.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ToHowEntities : DbContext
    {
        public ToHowEntities()
            : base("name=ToHowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbImage> tbImages { get; set; }
        public virtual DbSet<tbImageComment> tbImageComments { get; set; }
        public virtual DbSet<tbImageMeta> tbImageMetas { get; set; }
        public virtual DbSet<tbJobBoard> tbJobBoards { get; set; }
        public virtual DbSet<tbMetaType> tbMetaTypes { get; set; }
        public virtual DbSet<tbProfile> tbProfiles { get; set; }
        public virtual DbSet<tbRequest> tbRequests { get; set; }
        public virtual DbSet<tbUserImage> tbUserImages { get; set; }
    }
}
